# numpy code for machine learning

### import libraries:

In [2]:
import numpy as np
import pandas as pd

### make array with numpy:

#### make array with range

In [7]:
a=np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### make array without range

In [5]:
a=np.array(5)
a

array(5)

#### reshape array

In [15]:
a=a.reshape(3,5)

In [9]:
a.shape

(15,)

#### print attribute of array

In [21]:
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)

(3, 5)
2
15
int32


#### filter array

In [22]:
a>2

array([[False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

#### make zero array

In [30]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### make one array

In [31]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### make 3 dimention array 

In [32]:
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])